"""proxy.conf renderer + validate/apply pipeline (FreeRADIUS 3.2.x).

This module is the heart of the panel. It turns the DB records into a valid
FreeRADIUS 3.2 proxy.conf, optionally validates it with `radiusd -XC`, writes
it to the configured path and reloads the server.

Keeping all FreeRADIUS-specific syntax in one place means porting to
FreeRADIUS 4 (where proxy.conf is replaced by rlm_radius instances) is a matter
of swapping this renderer, not touching the API or the data model.
"""
from __future__ import annotations

import asyncio
import os
import re
import shlex
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from .config import get_settings
from .models import (
    Client,
    HomeServerPool,
    LdapSettings,
    RadiusSettings,
    PoolMember,
    Rule,
    TargetServer,
)

settings = get_settings()

INDENT = "\t"


def _quote_secret(secret: str) -> str:
    """Wrap the shared secret in double quotes, escaping as FreeRADIUS expects."""
    escaped = secret.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_home_server(hs: TargetServer) -> str:
    # A "target server" renders as FreeRADIUS `home_server {}` (FR syntax).
    lines = [f"home_server {hs.name} {{"]
    lines.append(f"{INDENT}type = {hs.type}")
    lines.append(f"{INDENT}ipaddr = {hs.ipaddr}")
    lines.append(f"{INDENT}port = {hs.port}")
    lines.append(f"{INDENT}secret = {_quote_secret(hs.secret)}")
    lines.append(
        f"{INDENT}require_message_authenticator = "
        f"{'yes' if hs.require_message_authenticator else 'no'}"
    )
    lines.append(f"{INDENT}response_window = {hs.response_window}")
    lines.append(f"{INDENT}zombie_period = {hs.zombie_period}")
    lines.append(f"{INDENT}revive_interval = {hs.revive_interval}")
    if hs.status_check and hs.status_check != "none":
        lines.append(f"{INDENT}status_check = {hs.status_check}")
        lines.append(f"{INDENT}check_interval = {hs.check_interval}")
        lines.append(f"{INDENT}num_answers_to_alive = {hs.num_answers_to_alive}")
    else:
        lines.append(f"{INDENT}status_check = none")
    lines.append("}")
    return "\n".join(lines)


FALLBACK_HOME_SERVER = "radiuspanel-fallback"
FALLBACK_VSERVER = "radiuspanel_fallback"


def render_pool(
    pool: HomeServerPool, member_names: list[str], *, fallback: bool = False
) -> str:
    lines = [f"home_server_pool {pool.name} {{"]
    lines.append(f"{INDENT}type = {pool.type}")
    if not member_names:
        lines.append(f"{INDENT}# WARNING: pool has no home_server members")
    for name in member_names:
        lines.append(f"{INDENT}home_server = {name}")
    if fallback:
        # Used only when every real member is dead → local AD 1st-factor (ADR-0009).
        lines.append(f"{INDENT}fallback = {FALLBACK_HOME_SERVER}")
    lines.append("}")
    return "\n".join(lines)


def render_realm_for_pool(pool_name: str) -> str:
    """One realm per pool — pure proxy plumbing. Routing is chosen per client
    (radiuspanel_route sets Proxy-To-Realm to this realm), not by User-Name, so
    the realm name just mirrors the pool name (ADR-0003)."""
    return (
        f"realm {pool_name} {{\n"
        f"{INDENT}pool = {pool_name}\n"
        f"{INDENT}nostrip\n"
        "}"
    )


def _quote(value: str) -> str:
    """Single-quote a value for FreeRADIUS, escaping embedded quotes."""
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


PASSWORD_MASK = "********"

LDAP_HEADER = """#
# mods-enabled/ldap — generated by FreeRADIUS Proxy Panel
# Generated: {ts}
#
# DO NOT EDIT BY HAND. Overwritten on the next apply.
# Target: FreeRADIUS 3.2.x (rlm_ldap). AD group gate — see docs/adr/0001.
#
"""


def render_ldap_module(cfg: LdapSettings, *, mask_password: bool = False) -> str:
    """Render the AD/LDAP module (mods-enabled/ldap) for the group gate.

    When `mask_password` is True the bind password is replaced with a mask —
    used for the UI preview so the secret is never shipped to the browser.
    """
    scheme = "ldaps://" if cfg.use_ldaps else ""
    port = cfg.port or (636 if cfg.use_ldaps else 389)
    password = PASSWORD_MASK if mask_password else cfg.bind_password

    lines = [LDAP_HEADER.format(ts=datetime.now(timezone.utc).isoformat())]
    lines.append("ldap {")
    lines.append(f"{INDENT}server = {_quote(scheme + cfg.server)}")
    lines.append(f"{INDENT}port = {port}")
    lines.append(f"{INDENT}identity = {_quote(cfg.bind_dn)}")
    lines.append(f"{INDENT}password = {_quote(password)}")
    lines.append(f"{INDENT}base_dn = {_quote(cfg.base_dn)}")
    lines.append("")
    # User lookup for password bind (the 2FA pool-down fallback, ADR-0009).
    # Double quotes so %{User-Name} is xlat-expanded (single quotes = literal).
    lines.append(f"{INDENT}# user auth (bind) — AD sAMAccountName")
    lines.append(f"{INDENT}user {{")
    lines.append(f"{INDENT}{INDENT}base_dn = {_quote(cfg.base_dn)}")
    lines.append(f'{INDENT}{INDENT}filter = "(sAMAccountName=%{{User-Name}})"')
    lines.append(f"{INDENT}}}")
    lines.append("")
    lines.append(f"{INDENT}# group membership check — per-realm required group")
    lines.append(f"{INDENT}group {{")
    group_base = cfg.group_base_dn or cfg.base_dn
    lines.append(f"{INDENT}{INDENT}base_dn = {_quote(group_base)}")
    lines.append(f"{INDENT}{INDENT}filter = {_quote(cfg.group_filter)}")
    lines.append(
        f"{INDENT}{INDENT}membership_attribute = "
        f"{_quote(cfg.group_membership_attribute)}"
    )
    # Cache the resolved membership so we don't hit AD on every packet.
    lines.append(f"{INDENT}{INDENT}cacheable_name = yes")
    lines.append(f"{INDENT}}}")
    lines.append("")
    lines.append(f"{INDENT}options {{")
    lines.append(f"{INDENT}{INDENT}net_timeout = {cfg.net_timeout}")
    lines.append(f"{INDENT}{INDENT}timeout = {cfg.net_timeout}")
    lines.append(f"{INDENT}{INDENT}res_timeout = {cfg.net_timeout}")
    lines.append(f"{INDENT}}}")
    if cfg.use_ldaps or cfg.start_tls:
        lines.append("")
        lines.append(f"{INDENT}tls {{")
        if cfg.start_tls and not cfg.use_ldaps:
            lines.append(f"{INDENT}{INDENT}start_tls = yes")
        if cfg.ca_cert.strip():
            lines.append(f"{INDENT}{INDENT}ca_file = {_quote(settings.ldap_ca_path)}")
        lines.append(f"{INDENT}{INDENT}require_cert = '{cfg.tls_require_cert}'")
        if cfg.tls_min_version:
            lines.append(
                f"{INDENT}{INDENT}tls_min_version = {_quote(cfg.tls_min_version)}"
            )
        lines.append(f"{INDENT}}}")
    lines.append(f"{INDENT}# membership cache TTL (s): {cfg.cache_ttl}")
    # Lazy connection pool: start=0 so FreeRADIUS boots even when AD is
    # unreachable (fail-open philosophy — an AD outage must not stop the server).
    lines.append(f"{INDENT}pool {{")
    lines.append(f"{INDENT}{INDENT}start = 0")
    lines.append(f"{INDENT}{INDENT}min = 0")
    lines.append(f"{INDENT}{INDENT}spare = 1")
    lines.append(f"{INDENT}{INDENT}max = 5")
    lines.append(f"{INDENT}{INDENT}idle_timeout = 60")
    lines.append(f"{INDENT}}}")
    lines.append("}")
    return "\n".join(lines) + "\n"


CLIENTS_HEADER = """#
# clients.conf — generated by FreeRADIUS Proxy Panel
# Generated: {ts}
#
# DO NOT EDIT BY HAND. Overwritten on the next apply.
# Target: FreeRADIUS 3.2.x. These are the request originators (NAS): the
# VMware UAG / VPN / WiFi devices allowed to send us requests.
#
"""


def render_client(c: Client) -> str:
    lines = [f"client {c.name} {{"]
    lines.append(f"{INDENT}ipaddr = {c.ipaddr}")
    lines.append(f"{INDENT}secret = {_quote_secret(c.secret)}")
    lines.append(f"{INDENT}shortname = {c.shortname or c.name}")
    lines.append(f"{INDENT}nastype = {c.nas_type}")
    if c.proto and c.proto != "udp":
        lines.append(f"{INDENT}proto = {c.proto}")
    lines.append(
        f"{INDENT}require_message_authenticator = "
        f"{c.require_message_authenticator}"
    )
    # Custom field read by policy.d/radiuspanel via %{client:preserve_source_ip}.
    if c.preserve_source_ip:
        lines.append(f"{INDENT}preserve_source_ip = yes")
    lines.append("}")
    return "\n".join(lines)


async def render_clients_conf(db: AsyncSession) -> str:
    rows = (
        await db.execute(
            select(Client).where(Client.enabled).order_by(Client.name)
        )
    ).scalars().all()
    parts = [CLIENTS_HEADER.format(ts=datetime.now(timezone.utc).isoformat())]
    if not rows:
        parts.append("# WARNING: no clients defined — FreeRADIUS will drop all\n"
                     "# incoming requests (every source is an unknown client).\n")
    for c in rows:
        parts.append(render_client(c))
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


POLICY_HEADER = """#
# policy.d/radiuspanel — generated by FreeRADIUS Proxy Panel
# Generated: {ts}
#
# DO NOT EDIT BY HAND. Overwritten on the next apply.
# Target: FreeRADIUS 3.2.x. Named policies for the panel. Wire them into your
# virtual server ONCE (they are not called automatically):
#   authorize {{ ... radiuspanel_route ... }}   (ordered rules: route + AD gate)
#   pre-proxy {{ ... radiuspanel_srcip ... }}
#   post-auth {{ ... radiuspanel_log ... }}     (also in Post-Auth-Type REJECT)
#
"""


SQL_HEADER = """#
# mods-enabled/sql — generated by FreeRADIUS Proxy Panel
# Generated: {ts}
#
# DO NOT EDIT BY HAND. Overwritten on the next apply.
# Points at the panel's own Postgres. Used by radiuspanel_route (AD gate) and
# radiuspanel_log via the %{{sql:...}} xlat (ADR-0002/0004).
#
"""


def render_sql_module() -> str:
    s = settings
    return SQL_HEADER.format(ts=datetime.now(timezone.utc).isoformat()) + (
        "sql {\n"
        f'{INDENT}driver = "rlm_sql_postgresql"\n'
        f'{INDENT}dialect = "postgresql"\n'
        f'{INDENT}server = "{s.sql_db_host}"\n'
        f"{INDENT}port = {s.sql_db_port}\n"
        f'{INDENT}login = "{s.sql_db_login}"\n'
        f'{INDENT}password = "{s.sql_db_password}"\n'
        f'{INDENT}radius_db = "{s.sql_db_name}"\n'
        f"{INDENT}read_clients = no\n"
        f"{INDENT}pool {{\n"
        f"{INDENT}{INDENT}start = 1\n"
        f"{INDENT}{INDENT}min = 1\n"
        f"{INDENT}{INDENT}max = 5\n"
        f"{INDENT}{INDENT}idle_timeout = 60\n"
        f"{INDENT}}}\n"
        "}\n"
    )


def _sql_lit(value: str) -> str:
    """Escape a single-quoted SQL literal (our own config values)."""
    return value.replace("'", "''")


def _normalized_username(mode: str) -> str:
    """unlang expression that yields the lower-cased username to match in AD."""
    if mode == "strip_realm":
        # suffix module puts the realm-stripped name in Stripped-User-Name.
        return "%{tolower:%{%{Stripped-User-Name}:-%{User-Name}}}"
    if mode == "strip_ntdomain":
        # DOMAIN\\user -> user (fall back to whole name if no backslash).
        return "%{tolower:%{%{1}:-%{User-Name}}}"
    return "%{tolower:%{User-Name}}"


def _wildcard_to_regex(pattern: str) -> str:
    """Glob → anchored regex. `*` becomes `.*`; everything else is escaped."""
    out = []
    for ch in pattern:
        if ch == "*":
            out.append(".*")
        elif ch in ".^$+?()[]{}|\\/":
            out.append("\\" + ch)
        else:
            out.append(ch)
    return "^" + "".join(out) + "$"


def _render_gate_body(rule: Rule, depth: int) -> list[str]:
    """AD group gate lines for a rule (inside its if-block). Keyed by the group
    DN; sets &Tmp-String-1 to the result for the decision log."""
    g = _sql_lit(rule.required_ad_group_dn)
    i = INDENT * depth
    norm = _normalized_username(rule.username_normalization)
    lines = []
    if rule.username_normalization == "strip_ntdomain":
        lines.append(f'{i}if (&User-Name =~ /^[^\\\\]*\\\\(.+)$/) {{ }}')
    lines.append(f'{i}update request {{ &Tmp-String-0 := "{norm}" }}')
    lines.append(f"{i}if (&Tmp-String-0 !~ /^[a-z0-9._@-]+$/) {{")
    lines.append(f'{i}{INDENT}update request {{ &Tmp-String-1 := "reject-baduser" }}')
    lines.append(f"{i}{INDENT}reject")
    lines.append(f"{i}}}")
    member_q = (
        "%{sql:SELECT 1 FROM ad_group_member WHERE group_dn='" + g
        + "' AND username='%{Tmp-String-0}' LIMIT 1}"
    )
    status_q = "%{sql:SELECT status FROM ad_group_sync WHERE group_dn='" + g + "'}"
    lines.append(f'{i}if ("{member_q}" == "1") {{')
    lines.append(f'{i}{INDENT}update request {{ &Tmp-String-1 := "pass" }}')
    lines.append(f"{i}}}")
    lines.append(f"{i}else {{")
    lines.append(f'{i}{INDENT}if ("{status_q}" == "ok") {{')
    lines.append(f'{i}{INDENT*2}update request {{ &Tmp-String-1 := "reject" }}')
    lines.append(f"{i}{INDENT*2}reject")
    lines.append(f"{i}{INDENT}}}")
    if rule.ad_fail_mode == "closed":
        lines.append(f"{i}{INDENT}else {{")
        lines.append(f'{i}{INDENT*2}update request {{ &Tmp-String-1 := "reject-failclosed" }}')
        lines.append(f"{i}{INDENT*2}reject")
        lines.append(f"{i}{INDENT}}}")
    else:
        lines.append(f"{i}{INDENT}else {{")
        lines.append(f'{i}{INDENT*2}update request {{ &Tmp-String-1 := "skip-faildopen" }}')
        lines.append(f"{i}{INDENT}}}")
    lines.append(f"{i}}}")
    return lines


def _render_rule(rule: Rule, first: bool) -> list[str]:
    """One rule as an if/elsif block: match client [+ username], route to pool,
    run the AD gate. First-match-wins via the elsif chain (ADR-0004)."""
    i = INDENT
    kw = "if" if first else "elsif"
    sn = (rule.client.shortname or rule.client.name) if rule.client else ""
    cond = f'&Client-Shortname == "{sn}"'
    if rule.match_username:
        cond += f' && &User-Name =~ /{_wildcard_to_regex(rule.match_username)}/i'
    lines = [f"{i}{kw} ({cond}) {{"]
    lines.append(f'{i}{i}# rule: {rule.name or ("#" + str(rule.id))}')
    if rule.target_pool is not None:
        lines.append(f"{i}{i}update control {{")
        lines.append(f'{i}{i}{i}&Proxy-To-Realm := "{rule.target_pool.name}"')
        lines.append(f"{i}{i}}}")
    else:
        lines.append(f'{i}{i}update request {{ &Tmp-String-1 := "reject-nopool" }}')
        lines.append(f"{i}{i}reject")
        lines.append(f"{i}}}")
        return lines
    if rule.ad_group_check and rule.required_ad_group_dn:
        lines += _render_gate_body(rule, 2)
    else:
        lines.append(f'{i}{i}update request {{ &Tmp-String-1 := "pass" }}')
    lines.append(f"{i}}}")
    return lines


async def render_policy_conf(db: AsyncSession) -> str:
    """Render policy.d/radiuspanel — named unlang policies.

    radiuspanel_route: ordered rules (ADR-0004) — first match by client [+
    username wildcard] routes to its pool and runs the AD gate (sql membership
    + fail mode). No match -> reject.
    radiuspanel_srcip: preserve originator IP (per-client). radiuspanel_log:
    decision row into proxy_decision.
    """
    parts = [POLICY_HEADER.format(ts=datetime.now(timezone.utc).isoformat())]

    # Ordered rules (ADR-0004): first match wins. Each rule matches a client
    # (optionally + a username wildcard), routes to its pool and runs the AD
    # gate. Call radiuspanel_route in authorize. No match -> reject.
    rules = (
        await db.execute(
            select(Rule)
            .where(Rule.enabled)
            .options(selectinload(Rule.client), selectinload(Rule.target_pool))
            .order_by(Rule.position)
        )
    ).scalars().all()
    rules = [r for r in rules if r.client and r.client.enabled]

    route_body: list[str] = []
    if not rules:
        route_body.append(f"{INDENT}# no rules — nothing is proxied")
        route_body.append(f'{INDENT}update request {{ &Tmp-String-1 := "no-rule" }}')
        route_body.append(f"{INDENT}reject")
    else:
        for idx, rule in enumerate(rules):
            route_body += _render_rule(rule, first=(idx == 0))
        route_body.append(f"{INDENT}else {{")
        route_body.append(
            f'{INDENT}{INDENT}update request {{ &Tmp-String-1 := "no-rule" }}'
        )
        route_body.append(f"{INDENT}{INDENT}reject")
        route_body.append(f"{INDENT}}}")
    parts.append("radiuspanel_route {\n" + "\n".join(route_body) + "\n}\n")

    parts.append(
        "radiuspanel_srcip {\n"
        f"{INDENT}# Inject the real originator IP if the NAS did not set one.\n"
        f'{INDENT}if ("%{{client:preserve_source_ip}}" == "yes") {{\n'
        f"{INDENT}{INDENT}if (!&NAS-IP-Address) {{\n"
        f"{INDENT}{INDENT}{INDENT}update proxy-request {{\n"
        f"{INDENT}{INDENT}{INDENT}{INDENT}"
        '&NAS-IP-Address := "%{Packet-Src-IP-Address}"\n'
        f"{INDENT}{INDENT}{INDENT}}}\n"
        f"{INDENT}{INDENT}}}\n"
        f"{INDENT}}}\n"
        "}\n"
    )

    # Decision log — one row per request into proxy_decision (panel reads it).
    # Wire radiuspanel_log into post-auth AND Post-Auth-Type REJECT of your site.
    # User-Name is charset-guarded before the INSERT (injection defence); other
    # fields are IPs / our own config / reply enum.
    i = INDENT
    insert = (
        "%{sql:INSERT INTO proxy_decision "
        "(nas_ip, packet_src_ip, username, realm, ad_result, reply) VALUES "
        "('%{NAS-IP-Address}', '%{Packet-Src-IP-Address}', "
        "'%{tolower:%{User-Name}}', '%{control:Proxy-To-Realm}', "
        "'%{%{Tmp-String-1}:-n-a}', '%{reply:Packet-Type}')}"
    )
    parts.append(
        "radiuspanel_log {\n"
        f"{i}if (&User-Name && \"%{{User-Name}}\" =~ /^[A-Za-z0-9._@-]+$/) {{\n"
        f'{i}{i}if ("{insert}" == "1") {{\n'
        f"{i}{i}{i}noop\n"
        f"{i}{i}}}\n"
        f"{i}}}\n"
        "}\n"
    )
    return "\n".join(parts)


HEADER = """#
# proxy.conf — generated by FreeRADIUS Proxy Panel
# Generated: {ts}
#
# DO NOT EDIT BY HAND. Changes made here are overwritten on the next apply.
# Target: FreeRADIUS 3.2.x
#
"""


async def _fallback_pool_names(db: AsyncSession) -> set[str]:
    """Pool names with an enabled `pool_down_fallback` rule — only when AD/LDAP
    is on (the fallback binds against it). Empty otherwise (feature off)."""
    ldap_cfg = await db.get(LdapSettings, 1)
    if not (ldap_cfg and ldap_cfg.enabled):
        return set()
    rows = (
        await db.execute(
            select(Rule)
            .where(Rule.enabled, Rule.pool_down_fallback)
            .options(selectinload(Rule.target_pool))
        )
    ).scalars().all()
    return {r.target_pool.name for r in rows if r.target_pool}


FALLBACK_SITE_HEADER = """#
# sites-enabled/radiuspanel-fallback — generated by FreeRADIUS Proxy Panel
# Generated: {ts}
#
# DO NOT EDIT BY HAND. Overwritten on the next apply.
# 2FA pool-down fallback (ADR-0009): when a target pool is fully dead, check the
# 1st factor (AD password, PAP) locally and ACCEPT. Deliberate 2FA bypass on
# outage — enabled per rule. Reached via home_server_pool "fallback".
#
"""


async def render_fallback_site() -> str:
    """The fallback virtual server. Gated by SQL so only clients with an enabled
    pool_down_fallback rule are let through; then AD user lookup + password bind."""
    i = INDENT
    gate = (
        "%{sql:SELECT 1 FROM rules r JOIN clients c ON c.id = r.client_id "
        "WHERE r.enabled AND r.pool_down_fallback "
        "AND c.shortname = '%{Client-Shortname}' LIMIT 1}"
    )
    # The fallback logs its own decision row directly (radiuspanel_log) with a
    # pool-down-* marker, so a 2FA bypass is always visible in Logs even though
    # the main server also records the proxied outcome.
    return FALLBACK_SITE_HEADER.format(ts=datetime.now(timezone.utc).isoformat()) + (
        f"server {FALLBACK_VSERVER} {{\n"
        f"{i}authorize {{\n"
        f'{i}{i}if ("{gate}" != "1") {{\n'
        f'{i}{i}{i}update request {{ &Tmp-String-1 := "pool-down-blocked" }}\n'
        f"{i}{i}{i}reject\n"
        f"{i}{i}}}\n"
        f"{i}{i}ldap\n"
        f"{i}{i}if (notfound || fail) {{\n"
        f'{i}{i}{i}update request {{ &Tmp-String-1 := "pool-down-nouser" }}\n'
        f"{i}{i}{i}reject\n"
        f"{i}{i}}}\n"
        f"{i}{i}if (!&control:Auth-Type) {{\n"
        f"{i}{i}{i}update control {{ &Auth-Type := LDAP }}\n"
        f"{i}{i}}}\n"
        f"{i}}}\n"
        f"{i}authenticate {{\n"
        f"{i}{i}Auth-Type LDAP {{\n"
        f"{i}{i}{i}ldap\n"
        f"{i}{i}}}\n"
        f"{i}}}\n"
        f"{i}post-auth {{\n"
        f'{i}{i}update request {{ &Tmp-String-1 := "pool-down-1fa" }}\n'
        f"{i}{i}radiuspanel_log\n"
        f"{i}{i}Post-Auth-Type REJECT {{\n"
        f'{i}{i}{i}update request {{ &Tmp-String-1 := "pool-down-reject" }}\n'
        f"{i}{i}{i}radiuspanel_log\n"
        f"{i}{i}}}\n"
        f"{i}}}\n"
        "}\n"
    )


async def render_proxy_conf(db: AsyncSession) -> str:
    """Build the full proxy.conf text from the current DB state.

    Routing is per-client (ADR-0003): one realm is generated per pool as proxy
    plumbing; the panel picks it via Proxy-To-Realm (radiuspanel_route), not by
    User-Name suffix.
    """
    ts_rows = (
        await db.execute(
            select(TargetServer)
            .where(TargetServer.enabled)
            .order_by(TargetServer.name)
        )
    ).scalars().all()

    pool_rows = (
        await db.execute(
            select(HomeServerPool)
            .where(HomeServerPool.enabled)
            .options(
                selectinload(HomeServerPool.members).selectinload(
                    PoolMember.target_server
                )
            )
            .order_by(HomeServerPool.name)
        )
    ).scalars().all()

    fb_pools = await _fallback_pool_names(db)

    parts: list[str] = [HEADER.format(ts=datetime.now(timezone.utc).isoformat())]

    parts.append("# ---- target servers ----\n")
    for ts in ts_rows:
        parts.append(render_home_server(ts))
        parts.append("")

    # Virtual home server for the 2FA pool-down fallback (local AD 1st factor).
    if fb_pools:
        parts.append(
            f"home_server {FALLBACK_HOME_SERVER} {{\n"
            f"{INDENT}virtual_server = {FALLBACK_VSERVER}\n"
            "}\n"
        )

    parts.append("# ---- pools ----\n")
    for pool in pool_rows:
        ordered = sorted(pool.members, key=lambda m: m.position)
        names = [m.target_server.name for m in ordered if m.target_server.enabled]
        parts.append(render_pool(pool, names, fallback=pool.name in fb_pools))
        parts.append("")

    parts.append("# ---- realms (one per pool; routing chosen per client) ----\n")
    for pool in pool_rows:
        parts.append(render_realm_for_pool(pool.name))
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


@dataclass
class ApplyResult:
    written_paths: list[str]
    validated: bool
    validation_output: str
    reloaded: bool
    reload_output: str


def _run_blocking(cmd: str) -> tuple[int, str]:
    proc = subprocess.run(
        shlex.split(cmd),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    return proc.returncode, proc.stdout


async def _run(cmd: str) -> tuple[int, str]:
    # Run in a worker thread via subprocess.run rather than
    # asyncio.create_subprocess_exec: under uvicorn's uvloop the asyncio child
    # watcher interacts badly with FreeRADIUS's double-forking daemon (apply
    # would take minutes / hang). A thread + blocking subprocess is reliable.
    return await asyncio.to_thread(_run_blocking, cmd)


class ConfigValidationError(Exception):
    def __init__(self, output: str):
        super().__init__("FreeRADIUS rejected the generated config")
        self.output = output


@dataclass
class _Backup:
    path: Path
    existed: bool
    content: str | None


def _write_with_backup(path: Path, content: str) -> _Backup:
    """Write `content` to `path`, returning enough state to roll back."""
    path.parent.mkdir(parents=True, exist_ok=True)
    existed = path.exists()
    backup = path.read_text() if existed else None
    path.write_text(content)
    return _Backup(path=path, existed=existed, content=backup)


def _rollback(backups: list[_Backup]) -> None:
    for b in backups:
        if b.existed:
            b.path.write_text(b.content or "")
        elif b.path.exists():
            os.unlink(b.path)


async def apply_config(db: AsyncSession) -> ApplyResult:
    """Render every managed file, write in place, validate once, roll back all
    on failure, then reload.

    The panel owns several FreeRADIUS files (proxy.conf, clients.conf, …).
    `radiusd -XC` validates the whole server config by its real paths, so we
    must write the *actual* target files, not side-copies. All files are backed
    up first; a validation failure rolls back every one of them, leaving the
    running server on its last known-good config until the reload step, which
    only runs after a pass.
    """
    targets: list[tuple[Path, str]] = [
        (Path(settings.proxy_conf_path), await render_proxy_conf(db)),
        (Path(settings.clients_conf_path), await render_clients_conf(db)),
        (Path(settings.policy_conf_path), await render_policy_conf(db)),
    ]

    # AD/LDAP module is written only when enabled. Its CA cert (if any) is
    # materialised first so the module's ca_file points at a real file.
    ldap_cfg = await db.get(LdapSettings, 1)
    if ldap_cfg and ldap_cfg.enabled:
        if ldap_cfg.ca_cert.strip():
            targets.append((Path(settings.ldap_ca_path), ldap_cfg.ca_cert))
        targets.append(
            (Path(settings.ldap_conf_path), render_ldap_module(ldap_cfg))
        )

    # The sql module is always written: the adgate uses it for membership and
    # radiuspanel_log uses it for the decision log. It points at the panel's own
    # Postgres, which is always up alongside the backend.
    targets.append((Path(settings.sql_conf_path), render_sql_module()))

    # Patch only the max_request_time line in the (stock) radiusd.conf from
    # RadiusSettings — it caps a target's response_window, so slow 2FA needs it
    # raised. Skip if the file or the setting isn't there (dev without raddb).
    radiusd_path = Path(settings.radiusd_conf_path)
    rad_cfg = await db.get(RadiusSettings, 1)
    if rad_cfg and radiusd_path.exists():
        cur = radiusd_path.read_text()
        patched = re.sub(
            r"(?m)^(\s*)max_request_time\s*=.*$",
            rf"\g<1>max_request_time = {int(rad_cfg.max_request_time)}",
            cur,
            count=1,
        )
        if patched != cur:
            targets.append((radiusd_path, patched))

    # 2FA pool-down fallback virtual server (ADR-0009): write when any rule
    # enables it (+ AD on); otherwise remove a stale file so -XC stays clean.
    fb_pools = await _fallback_pool_names(db)
    fb_path = Path(settings.fallback_site_path)
    if fb_pools:
        targets.append((fb_path, await render_fallback_site()))

    backups = [_write_with_backup(path, content) for path, content in targets]
    if not fb_pools and fb_path.exists():
        backups.append(_Backup(path=fb_path, existed=True, content=fb_path.read_text()))
        fb_path.unlink()

    validated = False
    validation_output = "validation skipped (RADIUS_CHECK_CMD not set)"
    if settings.radius_check_cmd:
        code, out = await _run(settings.radius_check_cmd)
        validation_output = out
        if code != 0:
            _rollback(backups)
            raise ConfigValidationError(out)
        validated = True

    reloaded = False
    reload_output = "reload skipped (RADIUS_RELOAD_CMD not set)"
    if settings.radius_reload_cmd:
        code, out = await _run(settings.radius_reload_cmd)
        reload_output = out
        reloaded = code == 0

    return ApplyResult(
        written_paths=[str(p) for p, _ in targets],
        validated=validated,
        validation_output=validation_output,
        reloaded=reloaded,
        reload_output=reload_output,
    )
