"""proxy.conf renderer + validate/apply pipeline (FreeRADIUS 3.2.x).

This module is the heart of the panel. It turns the DB records into a valid
FreeRADIUS 3.2 proxy.conf, optionally validates it with `radiusd -XC`, writes
it to the configured path and reloads the server.

Keeping all FreeRADIUS-specific syntax in one place means porting to
FreeRADIUS 4 (where proxy.conf is replaced by rlm_radius instances) is a matter
of swapping this renderer, not touching the API or the data model.
"""
from __future__ import annotations

import asyncio
import os
import shlex
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from .config import get_settings
from .models import (
    Client,
    HomeServerPool,
    LdapSettings,
    PoolMember,
    TargetServer,
)

settings = get_settings()

INDENT = "\t"


def _quote_secret(secret: str) -> str:
    """Wrap the shared secret in double quotes, escaping as FreeRADIUS expects."""
    escaped = secret.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_home_server(hs: TargetServer) -> str:
    # A "target server" renders as FreeRADIUS `home_server {}` (FR syntax).
    lines = [f"home_server {hs.name} {{"]
    lines.append(f"{INDENT}type = {hs.type}")
    lines.append(f"{INDENT}ipaddr = {hs.ipaddr}")
    lines.append(f"{INDENT}port = {hs.port}")
    lines.append(f"{INDENT}secret = {_quote_secret(hs.secret)}")
    lines.append(
        f"{INDENT}require_message_authenticator = "
        f"{'yes' if hs.require_message_authenticator else 'no'}"
    )
    lines.append(f"{INDENT}response_window = {hs.response_window}")
    lines.append(f"{INDENT}zombie_period = {hs.zombie_period}")
    lines.append(f"{INDENT}revive_interval = {hs.revive_interval}")
    if hs.status_check and hs.status_check != "none":
        lines.append(f"{INDENT}status_check = {hs.status_check}")
        lines.append(f"{INDENT}check_interval = {hs.check_interval}")
        lines.append(f"{INDENT}num_answers_to_alive = 3")
    else:
        lines.append(f"{INDENT}status_check = none")
    lines.append("}")
    return "\n".join(lines)


def render_pool(pool: HomeServerPool, member_names: list[str]) -> str:
    lines = [f"home_server_pool {pool.name} {{"]
    lines.append(f"{INDENT}type = {pool.type}")
    if not member_names:
        lines.append(f"{INDENT}# WARNING: pool has no home_server members")
    for name in member_names:
        lines.append(f"{INDENT}home_server = {name}")
    lines.append("}")
    return "\n".join(lines)


def render_realm_for_pool(pool_name: str) -> str:
    """One realm per pool — pure proxy plumbing. Routing is chosen per client
    (radiuspanel_route sets Proxy-To-Realm to this realm), not by User-Name, so
    the realm name just mirrors the pool name (ADR-0003)."""
    return (
        f"realm {pool_name} {{\n"
        f"{INDENT}pool = {pool_name}\n"
        f"{INDENT}nostrip\n"
        "}"
    )


def _quote(value: str) -> str:
    """Single-quote a value for FreeRADIUS, escaping embedded quotes."""
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


PASSWORD_MASK = "********"

LDAP_HEADER = """#
# mods-enabled/ldap — generated by FreeRADIUS Proxy Panel
# Generated: {ts}
#
# DO NOT EDIT BY HAND. Overwritten on the next apply.
# Target: FreeRADIUS 3.2.x (rlm_ldap). AD group gate — see docs/adr/0001.
#
"""


def render_ldap_module(cfg: LdapSettings, *, mask_password: bool = False) -> str:
    """Render the AD/LDAP module (mods-enabled/ldap) for the group gate.

    When `mask_password` is True the bind password is replaced with a mask —
    used for the UI preview so the secret is never shipped to the browser.
    """
    scheme = "ldaps://" if cfg.use_ldaps else ""
    port = cfg.port or (636 if cfg.use_ldaps else 389)
    password = PASSWORD_MASK if mask_password else cfg.bind_password

    lines = [LDAP_HEADER.format(ts=datetime.now(timezone.utc).isoformat())]
    lines.append("ldap {")
    lines.append(f"{INDENT}server = {_quote(scheme + cfg.server)}")
    lines.append(f"{INDENT}port = {port}")
    lines.append(f"{INDENT}identity = {_quote(cfg.bind_dn)}")
    lines.append(f"{INDENT}password = {_quote(password)}")
    lines.append(f"{INDENT}base_dn = {_quote(cfg.base_dn)}")
    lines.append("")
    lines.append(f"{INDENT}# group membership check — per-realm required group")
    lines.append(f"{INDENT}group {{")
    group_base = cfg.group_base_dn or cfg.base_dn
    lines.append(f"{INDENT}{INDENT}base_dn = {_quote(group_base)}")
    lines.append(f"{INDENT}{INDENT}filter = {_quote(cfg.group_filter)}")
    lines.append(
        f"{INDENT}{INDENT}membership_attribute = "
        f"{_quote(cfg.group_membership_attribute)}"
    )
    # Cache the resolved membership so we don't hit AD on every packet.
    lines.append(f"{INDENT}{INDENT}cacheable_name = yes")
    lines.append(f"{INDENT}}}")
    lines.append("")
    lines.append(f"{INDENT}options {{")
    lines.append(f"{INDENT}{INDENT}net_timeout = {cfg.net_timeout}")
    lines.append(f"{INDENT}{INDENT}timeout = {cfg.net_timeout}")
    lines.append(f"{INDENT}{INDENT}res_timeout = {cfg.net_timeout}")
    lines.append(f"{INDENT}}}")
    if cfg.use_ldaps or cfg.start_tls:
        lines.append("")
        lines.append(f"{INDENT}tls {{")
        if cfg.start_tls and not cfg.use_ldaps:
            lines.append(f"{INDENT}{INDENT}start_tls = yes")
        if cfg.ca_cert.strip():
            lines.append(f"{INDENT}{INDENT}ca_file = {_quote(settings.ldap_ca_path)}")
        lines.append(f"{INDENT}{INDENT}require_cert = '{cfg.tls_require_cert}'")
        if cfg.tls_min_version:
            lines.append(
                f"{INDENT}{INDENT}tls_min_version = {_quote(cfg.tls_min_version)}"
            )
        lines.append(f"{INDENT}}}")
    lines.append(f"{INDENT}# membership cache TTL (s): {cfg.cache_ttl}")
    # Lazy connection pool: start=0 so FreeRADIUS boots even when AD is
    # unreachable (fail-open philosophy — an AD outage must not stop the server).
    lines.append(f"{INDENT}pool {{")
    lines.append(f"{INDENT}{INDENT}start = 0")
    lines.append(f"{INDENT}{INDENT}min = 0")
    lines.append(f"{INDENT}{INDENT}spare = 1")
    lines.append(f"{INDENT}{INDENT}max = 5")
    lines.append(f"{INDENT}{INDENT}idle_timeout = 60")
    lines.append(f"{INDENT}}}")
    lines.append("}")
    return "\n".join(lines) + "\n"


CLIENTS_HEADER = """#
# clients.conf — generated by FreeRADIUS Proxy Panel
# Generated: {ts}
#
# DO NOT EDIT BY HAND. Overwritten on the next apply.
# Target: FreeRADIUS 3.2.x. These are the request originators (NAS): the
# VMware UAG / VPN / WiFi devices allowed to send us requests.
#
"""


def render_client(c: Client) -> str:
    lines = [f"client {c.name} {{"]
    lines.append(f"{INDENT}ipaddr = {c.ipaddr}")
    lines.append(f"{INDENT}secret = {_quote_secret(c.secret)}")
    lines.append(f"{INDENT}shortname = {c.shortname or c.name}")
    lines.append(f"{INDENT}nastype = {c.nas_type}")
    if c.proto and c.proto != "udp":
        lines.append(f"{INDENT}proto = {c.proto}")
    lines.append(
        f"{INDENT}require_message_authenticator = "
        f"{c.require_message_authenticator}"
    )
    # Custom fields read by policy.d/radiuspanel via %{client:...}.
    if c.preserve_source_ip:
        lines.append(f"{INDENT}preserve_source_ip = yes")
    # Routing: which pool's realm this client proxies to (radiuspanel_route).
    if c.target_pool is not None:
        lines.append(f"{INDENT}target_pool = {c.target_pool.name}")
    lines.append("}")
    return "\n".join(lines)


async def render_clients_conf(db: AsyncSession) -> str:
    rows = (
        await db.execute(
            select(Client)
            .where(Client.enabled)
            .options(selectinload(Client.target_pool))
            .order_by(Client.name)
        )
    ).scalars().all()
    parts = [CLIENTS_HEADER.format(ts=datetime.now(timezone.utc).isoformat())]
    if not rows:
        parts.append("# WARNING: no clients defined — FreeRADIUS will drop all\n"
                     "# incoming requests (every source is an unknown client).\n")
    for c in rows:
        parts.append(render_client(c))
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


POLICY_HEADER = """#
# policy.d/radiuspanel — generated by FreeRADIUS Proxy Panel
# Generated: {ts}
#
# DO NOT EDIT BY HAND. Overwritten on the next apply.
# Target: FreeRADIUS 3.2.x. Named policies for the panel. Wire them into your
# virtual server ONCE (they are not called automatically):
#   authorize {{ ... radiuspanel_route radiuspanel_adgate ... }}
#   pre-proxy {{ ... radiuspanel_srcip ... }}
#   post-auth {{ ... radiuspanel_log ... }}   (also in Post-Auth-Type REJECT)
#
"""


SQL_HEADER = """#
# mods-enabled/sql — generated by FreeRADIUS Proxy Panel
# Generated: {ts}
#
# DO NOT EDIT BY HAND. Overwritten on the next apply.
# Points at the panel's own Postgres. Used only by radiuspanel_adgate via the
# %{{sql:...}} xlat to check locally-synced AD group membership (ADR-0002).
#
"""


def render_sql_module() -> str:
    s = settings
    return SQL_HEADER.format(ts=datetime.now(timezone.utc).isoformat()) + (
        "sql {\n"
        f'{INDENT}driver = "rlm_sql_postgresql"\n'
        f'{INDENT}dialect = "postgresql"\n'
        f'{INDENT}server = "{s.sql_db_host}"\n'
        f"{INDENT}port = {s.sql_db_port}\n"
        f'{INDENT}login = "{s.sql_db_login}"\n'
        f'{INDENT}password = "{s.sql_db_password}"\n'
        f'{INDENT}radius_db = "{s.sql_db_name}"\n'
        f"{INDENT}read_clients = no\n"
        f"{INDENT}pool {{\n"
        f"{INDENT}{INDENT}start = 1\n"
        f"{INDENT}{INDENT}min = 1\n"
        f"{INDENT}{INDENT}max = 5\n"
        f"{INDENT}{INDENT}idle_timeout = 60\n"
        f"{INDENT}}}\n"
        "}\n"
    )


def _sql_lit(value: str) -> str:
    """Escape a single-quoted SQL literal (our own config values)."""
    return value.replace("'", "''")


def _normalized_username(mode: str) -> str:
    """unlang expression that yields the lower-cased username to match in AD."""
    if mode == "strip_realm":
        # suffix module puts the realm-stripped name in Stripped-User-Name.
        return "%{tolower:%{%{Stripped-User-Name}:-%{User-Name}}}"
    if mode == "strip_ntdomain":
        # DOMAIN\\user -> user (fall back to whole name if no backslash).
        return "%{tolower:%{%{1}:-%{User-Name}}}"
    return "%{tolower:%{User-Name}}"


def _render_adgate_client(client: Client) -> str:
    g = _sql_lit(client.required_ad_group)
    i = INDENT
    norm = _normalized_username(client.username_normalization)
    sn = client.shortname or client.name
    lines = [f'{i}if (&Client-Shortname == "{sn}") {{']
    if client.username_normalization == "strip_ntdomain":
        lines.append(f'{i}{i}if (&User-Name =~ /^[^\\\\]*\\\\(.+)$/) {{ }}')
    lines.append(f'{i}{i}update request {{ &Tmp-String-0 := "{norm}" }}')
    # Injection guard: only expected username characters reach the sql xlat.
    lines.append(f"{i}{i}if (&Tmp-String-0 !~ /^[a-z0-9._@-]+$/) {{")
    lines.append(f"{i}{i}{i}reject")
    lines.append(f"{i}{i}}}")
    member_q = (
        "%{sql:SELECT 1 FROM ad_group_member WHERE group_dn='" + g
        + "' AND username='%{Tmp-String-0}' LIMIT 1}"
    )
    status_q = "%{sql:SELECT status FROM ad_group_sync WHERE group_dn='" + g + "'}"
    # &Tmp-String-1 carries the gate result for the decision log (radiuspanel_log).
    lines.append(f'{i}{i}if ("{member_q}" == "1") {{')
    lines.append(f'{i}{i}{i}update request {{ &Tmp-String-1 := "pass" }}')
    lines.append(f"{i}{i}}}")
    lines.append(f"{i}{i}else {{")
    lines.append(f'{i}{i}{i}# not in the locally-synced member list')
    lines.append(f'{i}{i}{i}if ("{status_q}" == "ok") {{')
    lines.append(f'{i}{i}{i}{i}update request {{ &Tmp-String-1 := "reject" }}')
    lines.append(f"{i}{i}{i}{i}reject")
    lines.append(f"{i}{i}{i}}}")
    if client.ad_fail_mode == "closed":
        lines.append(f"{i}{i}{i}else {{")
        lines.append(f"{i}{i}{i}{i}# fail-closed: no valid sync -> deny")
        lines.append(f'{i}{i}{i}{i}update request {{ &Tmp-String-1 := "reject-failclosed" }}')
        lines.append(f"{i}{i}{i}{i}reject")
        lines.append(f"{i}{i}{i}}}")
    else:
        lines.append(f"{i}{i}{i}else {{")
        lines.append(f"{i}{i}{i}{i}# fail-open: no valid sync -> allow (ADR-0002)")
        lines.append(f'{i}{i}{i}{i}update request {{ &Tmp-String-1 := "skip-faildopen" }}')
        lines.append(f"{i}{i}{i}}}")
    lines.append(f"{i}{i}}}")
    lines.append(f"{i}}}")
    return "\n".join(lines)


async def render_policy_conf(db: AsyncSession) -> str:
    """Render policy.d/radiuspanel — named unlang policies.

    radiuspanel_srcip: preserve originator IP for proxied requests (per-client,
    keyed on the client's preserve_source_ip flag). Runs in pre-proxy.
    radiuspanel_adgate: AD group gate per realm — checks the locally-synced
    membership (ad_group_member) via the sql xlat; on no-valid-sync it honours
    the realm's fail mode (ADR-0002).
    """
    parts = [POLICY_HEADER.format(ts=datetime.now(timezone.utc).isoformat())]

    # Routing by client (ADR-0003): set Proxy-To-Realm from the client's pool.
    # Call radiuspanel_route in authorize. User-Name plays no part in routing.
    parts.append(
        "radiuspanel_route {\n"
        f"{INDENT}# Route this client's request to its target pool.\n"
        f'{INDENT}if ("%{{client:target_pool}}") {{\n'
        f"{INDENT}{INDENT}update control {{\n"
        f'{INDENT}{INDENT}{INDENT}&Proxy-To-Realm := "%{{client:target_pool}}"\n'
        f"{INDENT}{INDENT}}}\n"
        f"{INDENT}}}\n"
        "}\n"
    )

    parts.append(
        "radiuspanel_srcip {\n"
        f"{INDENT}# Inject the real originator IP if the NAS did not set one.\n"
        f'{INDENT}if ("%{{client:preserve_source_ip}}" == "yes") {{\n'
        f"{INDENT}{INDENT}if (!&NAS-IP-Address) {{\n"
        f"{INDENT}{INDENT}{INDENT}update proxy-request {{\n"
        f"{INDENT}{INDENT}{INDENT}{INDENT}"
        '&NAS-IP-Address := "%{Packet-Src-IP-Address}"\n'
        f"{INDENT}{INDENT}{INDENT}}}\n"
        f"{INDENT}{INDENT}}}\n"
        f"{INDENT}}}\n"
        "}\n"
    )

    gated = (
        await db.execute(
            select(Client)
            .where(Client.ad_group_check, Client.enabled, Client.required_ad_group != "")
            .order_by(Client.name)
        )
    ).scalars().all()

    body = [f"{INDENT}# AD group gate per client — locally-synced membership (ADR-0002/3)"]
    if not gated:
        body.append(f"{INDENT}noop")
    else:
        for client in gated:
            body.append(_render_adgate_client(client))
    parts.append("radiuspanel_adgate {\n" + "\n".join(body) + "\n}\n")

    # Decision log — one row per request into proxy_decision (panel reads it).
    # Wire radiuspanel_log into post-auth AND Post-Auth-Type REJECT of your site.
    # User-Name is charset-guarded before the INSERT (injection defence); other
    # fields are IPs / our own config / reply enum.
    i = INDENT
    insert = (
        "%{sql:INSERT INTO proxy_decision "
        "(nas_ip, packet_src_ip, username, realm, ad_result, reply) VALUES "
        "('%{NAS-IP-Address}', '%{Packet-Src-IP-Address}', "
        "'%{tolower:%{User-Name}}', '%{control:Proxy-To-Realm}', "
        "'%{%{Tmp-String-1}:-n-a}', '%{reply:Packet-Type}')}"
    )
    parts.append(
        "radiuspanel_log {\n"
        f"{i}if (&User-Name && \"%{{User-Name}}\" =~ /^[A-Za-z0-9._@-]+$/) {{\n"
        f'{i}{i}if ("{insert}" == "1") {{\n'
        f"{i}{i}{i}noop\n"
        f"{i}{i}}}\n"
        f"{i}}}\n"
        "}\n"
    )
    return "\n".join(parts)


HEADER = """#
# proxy.conf — generated by FreeRADIUS Proxy Panel
# Generated: {ts}
#
# DO NOT EDIT BY HAND. Changes made here are overwritten on the next apply.
# Target: FreeRADIUS 3.2.x
#
"""


async def render_proxy_conf(db: AsyncSession) -> str:
    """Build the full proxy.conf text from the current DB state.

    Routing is per-client (ADR-0003): one realm is generated per pool as proxy
    plumbing; the panel picks it via Proxy-To-Realm (radiuspanel_route), not by
    User-Name suffix.
    """
    ts_rows = (
        await db.execute(
            select(TargetServer)
            .where(TargetServer.enabled)
            .order_by(TargetServer.name)
        )
    ).scalars().all()

    pool_rows = (
        await db.execute(
            select(HomeServerPool)
            .where(HomeServerPool.enabled)
            .options(
                selectinload(HomeServerPool.members).selectinload(
                    PoolMember.target_server
                )
            )
            .order_by(HomeServerPool.name)
        )
    ).scalars().all()

    parts: list[str] = [HEADER.format(ts=datetime.now(timezone.utc).isoformat())]

    parts.append("# ---- target servers ----\n")
    for ts in ts_rows:
        parts.append(render_home_server(ts))
        parts.append("")

    parts.append("# ---- pools ----\n")
    for pool in pool_rows:
        ordered = sorted(pool.members, key=lambda m: m.position)
        names = [m.target_server.name for m in ordered if m.target_server.enabled]
        parts.append(render_pool(pool, names))
        parts.append("")

    parts.append("# ---- realms (one per pool; routing chosen per client) ----\n")
    for pool in pool_rows:
        parts.append(render_realm_for_pool(pool.name))
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


@dataclass
class ApplyResult:
    written_paths: list[str]
    validated: bool
    validation_output: str
    reloaded: bool
    reload_output: str


def _run_blocking(cmd: str) -> tuple[int, str]:
    proc = subprocess.run(
        shlex.split(cmd),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    return proc.returncode, proc.stdout


async def _run(cmd: str) -> tuple[int, str]:
    # Run in a worker thread via subprocess.run rather than
    # asyncio.create_subprocess_exec: under uvicorn's uvloop the asyncio child
    # watcher interacts badly with FreeRADIUS's double-forking daemon (apply
    # would take minutes / hang). A thread + blocking subprocess is reliable.
    return await asyncio.to_thread(_run_blocking, cmd)


class ConfigValidationError(Exception):
    def __init__(self, output: str):
        super().__init__("FreeRADIUS rejected the generated config")
        self.output = output


@dataclass
class _Backup:
    path: Path
    existed: bool
    content: str | None


def _write_with_backup(path: Path, content: str) -> _Backup:
    """Write `content` to `path`, returning enough state to roll back."""
    path.parent.mkdir(parents=True, exist_ok=True)
    existed = path.exists()
    backup = path.read_text() if existed else None
    path.write_text(content)
    return _Backup(path=path, existed=existed, content=backup)


def _rollback(backups: list[_Backup]) -> None:
    for b in backups:
        if b.existed:
            b.path.write_text(b.content or "")
        elif b.path.exists():
            os.unlink(b.path)


async def apply_config(db: AsyncSession) -> ApplyResult:
    """Render every managed file, write in place, validate once, roll back all
    on failure, then reload.

    The panel owns several FreeRADIUS files (proxy.conf, clients.conf, …).
    `radiusd -XC` validates the whole server config by its real paths, so we
    must write the *actual* target files, not side-copies. All files are backed
    up first; a validation failure rolls back every one of them, leaving the
    running server on its last known-good config until the reload step, which
    only runs after a pass.
    """
    targets: list[tuple[Path, str]] = [
        (Path(settings.proxy_conf_path), await render_proxy_conf(db)),
        (Path(settings.clients_conf_path), await render_clients_conf(db)),
        (Path(settings.policy_conf_path), await render_policy_conf(db)),
    ]

    # AD/LDAP module is written only when enabled. Its CA cert (if any) is
    # materialised first so the module's ca_file points at a real file.
    ldap_cfg = await db.get(LdapSettings, 1)
    if ldap_cfg and ldap_cfg.enabled:
        if ldap_cfg.ca_cert.strip():
            targets.append((Path(settings.ldap_ca_path), ldap_cfg.ca_cert))
        targets.append(
            (Path(settings.ldap_conf_path), render_ldap_module(ldap_cfg))
        )

    # The sql module is always written: the adgate uses it for membership and
    # radiuspanel_log uses it for the decision log. It points at the panel's own
    # Postgres, which is always up alongside the backend.
    targets.append((Path(settings.sql_conf_path), render_sql_module()))

    backups = [_write_with_backup(path, content) for path, content in targets]

    validated = False
    validation_output = "validation skipped (RADIUS_CHECK_CMD not set)"
    if settings.radius_check_cmd:
        code, out = await _run(settings.radius_check_cmd)
        validation_output = out
        if code != 0:
            _rollback(backups)
            raise ConfigValidationError(out)
        validated = True

    reloaded = False
    reload_output = "reload skipped (RADIUS_RELOAD_CMD not set)"
    if settings.radius_reload_cmd:
        code, out = await _run(settings.radius_reload_cmd)
        reload_output = out
        reloaded = code == 0

    return ApplyResult(
        written_paths=[str(p) for p, _ in targets],
        validated=validated,
        validation_output=validation_output,
        reloaded=reloaded,
        reload_output=reload_output,
    )
